databaseType = "PostgreSql"
id = "7fb234bb-9043-403d-92ff-cfba1eac3c4b"
name = "POCFlyway"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.dev]
url = "jdbc:postgresql://localhost:5433/postgres"
schemas = [ "public" ]

[environments.stg]
url = "jdbc:postgresql://localhost:5432/userrole"
schemas = [ "public" ]
